config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get 'homes/top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>

<p class="alert">
<% if @book.errors.any? %>
    <%= @book.errors.count %> error prohibited this book from being saved:
    <% @book.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
<% end %>
</p>

<%= form_with model:@book, local:true do |f| %>

<div class="input">
  <label>Title:</label>
  <%= f.text_field :title %>
</div>

<div class="input">
  <label>Body:</label>
  <%= f.text_area :body %>
</div>

<div class="submit">
  <%= f.submit 'Update Book' %>
</div>

<% end %>

<%= link_to 'Show', book_path %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h2>Books</h2>

<table>
    <tr>
        <th class="tb-title">Title</th>
        <th class="tb-body">Body</th>
        <th></th>
    </tr>
    <% @books.each do |book| %>
    <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td>
            <%= link_to 'Show', book_path(book.id) %>
            <%= link_to 'Edit', edit_book_path(book.id) %>
            <%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
        </td>
    </tr>
    <% end %>

</table>


<h2>New book</h2>

<p class="alert">
<% if @book.errors.any? %>
    <%= @book.errors.count %> error prohibited this book from being saved:
    <% @book.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
<% end %>
</p>

<%= form_with model:@book, local:true do |f| %>

  <div class="input">
    <label>Title</label>
    <%= f.text_field :title %>
  </div>

  <div class="input">
    <label>Body</label>
    <%= f.text_area :body %>
  </div>

  <div class="submit">
    <%= f.submit 'Create Book' %>
  </div>

<% end %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/homes/top.html.erb
<h1>
  ようこそ<strong>Bookers</strong>へ！
</h1>
<p>
  <p>
    <strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や
  </p>
  <p>
    印象を共有し交換することができます
  </p>
</p>
<p>
    <%= link_to 'start', books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice">
      <%= flash[:notice] %>
    </p>

    <%= yield %>
  </body>
</html>